# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  jaguar_serializer_cli:
    import: "package:jaguar_serializer_cli/builder.dart"
    builder_factories: ["jaguarSerializer"]
    build_extensions: {".dart": [".jser.dart"]}
    auto_apply: root_package
    build_to: source